# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/settings.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(451, 330)
        self.centralwidget = QtWidgets.QWidget(Settings)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 431, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.email_tab = QtWidgets.QWidget()
        self.email_tab.setObjectName("email_tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.email_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 419, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.save_email_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.save_email_btn.setObjectName("save_email_btn")
        self.gridLayout.addWidget(self.save_email_btn, 5, 6, 1, 1)
        self.del_email_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.del_email_btn.setObjectName("del_email_btn")
        self.gridLayout.addWidget(self.del_email_btn, 5, 3, 1, 1)
        self.email_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.email_le.setObjectName("email_le")
        self.gridLayout.addWidget(self.email_le, 1, 5, 1, 2)
        self.add_email_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.add_email_btn.setObjectName("add_email_btn")
        self.gridLayout.addWidget(self.add_email_btn, 5, 1, 1, 1)
        self.ssl_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.ssl_rbtn.setText("")
        self.ssl_rbtn.setObjectName("ssl_rbtn")
        self.gridLayout.addWidget(self.ssl_rbtn, 3, 5, 1, 1)
        self.sender_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sender_lab.setObjectName("sender_lab")
        self.gridLayout.addWidget(self.sender_lab, 4, 4, 1, 1)
        self.password_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.password_lab.setObjectName("password_lab")
        self.gridLayout.addWidget(self.password_lab, 2, 4, 1, 1)
        self.ssl_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ssl_lab.setObjectName("ssl_lab")
        self.gridLayout.addWidget(self.ssl_lab, 3, 4, 1, 1)
        self.email_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.email_lab.setObjectName("email_lab")
        self.gridLayout.addWidget(self.email_lab, 1, 4, 1, 1)
        self.password_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.password_le.setObjectName("password_le")
        self.gridLayout.addWidget(self.password_le, 2, 5, 1, 2)
        self.sender_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.sender_le.setObjectName("sender_le")
        self.gridLayout.addWidget(self.sender_le, 4, 5, 1, 2)
        self.ssl_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ssl_le.setObjectName("ssl_le")
        self.gridLayout.addWidget(self.ssl_le, 3, 6, 1, 1)
        self.default_email_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.default_email_btn.setObjectName("default_email_btn")
        self.gridLayout.addWidget(self.default_email_btn, 5, 0, 1, 1)
        self.email_list = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.email_list.setAutoFillBackground(False)
        self.email_list.setStyleSheet("background-color rgb(202, 208, 216)")
        self.email_list.setObjectName("email_list")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.email_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(1, 203, 31))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.email_list.addItem(item)
        self.gridLayout.addWidget(self.email_list, 1, 0, 4, 4)
        self.tips_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.tips_lab.setMaximumSize(QtCore.QSize(130, 15))
        self.tips_lab.setObjectName("tips_lab")
        self.gridLayout.addWidget(self.tips_lab, 0, 0, 1, 1)
        self.tabWidget.addTab(self.email_tab, "")
        self.time_tab = QtWidgets.QWidget()
        self.time_tab.setObjectName("time_tab")
        self.time_list = QtWidgets.QListWidget(self.time_tab)
        self.time_list.setGeometry(QtCore.QRect(10, 10, 231, 271))
        self.time_list.setObjectName("time_list")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.time_list.addItem(item)
        self.creater_reminder_btn = QtWidgets.QPushButton(self.time_tab)
        self.creater_reminder_btn.setGeometry(QtCore.QRect(250, 10, 75, 23))
        self.creater_reminder_btn.setObjectName("creater_reminder_btn")
        self.del_reminder_btn = QtWidgets.QPushButton(self.time_tab)
        self.del_reminder_btn.setGeometry(QtCore.QRect(250, 50, 75, 23))
        self.del_reminder_btn.setObjectName("del_reminder_btn")
        self.up_btn = QtWidgets.QPushButton(self.time_tab)
        self.up_btn.setGeometry(QtCore.QRect(250, 90, 75, 23))
        self.up_btn.setObjectName("up_btn")
        self.down_btn = QtWidgets.QPushButton(self.time_tab)
        self.down_btn.setGeometry(QtCore.QRect(250, 130, 71, 21))
        self.down_btn.setObjectName("down_btn")
        self.save_reminder_btn = QtWidgets.QPushButton(self.time_tab)
        self.save_reminder_btn.setGeometry(QtCore.QRect(250, 170, 75, 23))
        self.save_reminder_btn.setObjectName("save_reminder_btn")
        self.label = QtWidgets.QLabel(self.time_tab)
        self.label.setGeometry(QtCore.QRect(250, 210, 141, 31))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.time_tab, "")
        self.color_tab = QtWidgets.QWidget()
        self.color_tab.setObjectName("color_tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.color_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, -10, 361, 281))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.color_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.color_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.color_gridLayout.setObjectName("color_gridLayout")
        self.red_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.red_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.red_le.setObjectName("red_le")
        self.color_gridLayout.addWidget(self.red_le, 1, 3, 1, 1)
        self.rgb_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.rgb_le.setObjectName("rgb_le")
        self.color_gridLayout.addWidget(self.rgb_le, 5, 1, 1, 1)
        self.bule_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.bule_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bule_le.setText("")
        self.bule_le.setMaxLength(3)
        self.bule_le.setObjectName("bule_le")
        self.color_gridLayout.addWidget(self.bule_le, 3, 3, 1, 1)
        self.priority_listWidget = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        self.priority_listWidget.setMinimumSize(QtCore.QSize(0, 180))
        self.priority_listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.priority_listWidget.setObjectName("priority_listWidget")
        self.color_gridLayout.addWidget(self.priority_listWidget, 1, 0, 3, 2)
        self.green_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.green_le.setMaximumSize(QtCore.QSize(50, 16777215))
        self.green_le.setObjectName("green_le")
        self.color_gridLayout.addWidget(self.green_le, 2, 3, 1, 1)
        self.red_Slider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.red_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.red_Slider.setObjectName("red_Slider")
        self.color_gridLayout.addWidget(self.red_Slider, 1, 2, 1, 1)
        self.green_Slider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.green_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.green_Slider.setObjectName("green_Slider")
        self.color_gridLayout.addWidget(self.green_Slider, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.color_gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.priority_save_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.priority_save_btn.setMinimumSize(QtCore.QSize(15, 0))
        self.priority_save_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        self.priority_save_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.priority_save_btn.setObjectName("priority_save_btn")
        self.color_gridLayout.addWidget(self.priority_save_btn, 5, 3, 1, 1)
        self.bule_Slider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.bule_Slider.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.bule_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.bule_Slider.setObjectName("bule_Slider")
        self.color_gridLayout.addWidget(self.bule_Slider, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.color_gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.color_Slider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.color_Slider.setOrientation(QtCore.Qt.Vertical)
        self.color_Slider.setObjectName("color_Slider")
        self.color_gridLayout.addWidget(self.color_Slider, 1, 4, 3, 1)
        self.tabWidget.addTab(self.color_tab, "")
        Settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.save_email_btn.setText(_translate("Settings", "保存"))
        self.del_email_btn.setText(_translate("Settings", "删除"))
        self.add_email_btn.setText(_translate("Settings", "添加"))
        self.sender_lab.setText(_translate("Settings", "发信名称"))
        self.password_lab.setText(_translate("Settings", "密码"))
        self.ssl_lab.setText(_translate("Settings", "ssl端口"))
        self.email_lab.setText(_translate("Settings", "Email地址"))
        self.default_email_btn.setText(_translate("Settings", "默认使用"))
        __sortingEnabled = self.email_list.isSortingEnabled()
        self.email_list.setSortingEnabled(False)
        item = self.email_list.item(0)
        item.setText(_translate("Settings", "furnace_0xg@163.com"))
        item = self.email_list.item(1)
        item.setText(_translate("Settings", "2057567309@qq,com"))
        self.email_list.setSortingEnabled(__sortingEnabled)
        self.tips_lab.setText(_translate("Settings", "暂仅支持stmp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.email_tab), _translate("Settings", "邮箱设置"))
        __sortingEnabled = self.time_list.isSortingEnabled()
        self.time_list.setSortingEnabled(False)
        item = self.time_list.item(0)
        item.setText(_translate("Settings", "15分钟"))
        self.time_list.setSortingEnabled(__sortingEnabled)
        self.creater_reminder_btn.setText(_translate("Settings", "添加"))
        self.del_reminder_btn.setText(_translate("Settings", "删除"))
        self.up_btn.setText(_translate("Settings", "上移"))
        self.down_btn.setText(_translate("Settings", "下降"))
        self.save_reminder_btn.setText(_translate("Settings", "保存"))
        self.label.setText(_translate("Settings", "前三个时间会\n"
"在主窗口的右键菜单显示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.time_tab), _translate("Settings", "提醒时间"))
        self.label_3.setText(_translate("Settings", "rgb:"))
        self.priority_save_btn.setText(_translate("Settings", "保存"))
        self.label_2.setText(_translate("Settings", "颜色设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.color_tab), _translate("Settings", "优先级颜色配置"))


