# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(494, 333)
        self.centralwidget = QtWidgets.QWidget(Settings)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 471, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.email_tab = QtWidgets.QWidget()
        self.email_tab.setObjectName("email_tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.email_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.save_email_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.save_email_btn.setObjectName("save_email_btn")
        self.gridLayout.addWidget(self.save_email_btn, 5, 6, 1, 1)
        self.del_email_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.del_email_btn.setObjectName("del_email_btn")
        self.gridLayout.addWidget(self.del_email_btn, 5, 3, 1, 1)
        self.email_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.email_le.setObjectName("email_le")
        self.gridLayout.addWidget(self.email_le, 1, 5, 1, 2)
        self.add_email_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.add_email_btn.setObjectName("add_email_btn")
        self.gridLayout.addWidget(self.add_email_btn, 5, 1, 1, 1)
        self.ssl_rbtn = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.ssl_rbtn.setText("")
        self.ssl_rbtn.setObjectName("ssl_rbtn")
        self.gridLayout.addWidget(self.ssl_rbtn, 3, 5, 1, 1)
        self.sender_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sender_lab.setObjectName("sender_lab")
        self.gridLayout.addWidget(self.sender_lab, 4, 4, 1, 1)
        self.password_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.password_lab.setObjectName("password_lab")
        self.gridLayout.addWidget(self.password_lab, 2, 4, 1, 1)
        self.ssl_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ssl_lab.setObjectName("ssl_lab")
        self.gridLayout.addWidget(self.ssl_lab, 3, 4, 1, 1)
        self.email_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.email_lab.setObjectName("email_lab")
        self.gridLayout.addWidget(self.email_lab, 1, 4, 1, 1)
        self.password_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.password_le.setObjectName("password_le")
        self.gridLayout.addWidget(self.password_le, 2, 5, 1, 2)
        self.sender_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.sender_le.setObjectName("sender_le")
        self.gridLayout.addWidget(self.sender_le, 4, 5, 1, 2)
        self.ssl_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ssl_le.setObjectName("ssl_le")
        self.gridLayout.addWidget(self.ssl_le, 3, 6, 1, 1)
        self.default_email_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.default_email_btn.setObjectName("default_email_btn")
        self.gridLayout.addWidget(self.default_email_btn, 5, 0, 1, 1)
        self.email_list = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.email_list.setAutoFillBackground(False)
        self.email_list.setStyleSheet("background-color rgb(202, 208, 216)")
        self.email_list.setObjectName("email_list")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.email_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(1, 203, 31))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.email_list.addItem(item)
        self.gridLayout.addWidget(self.email_list, 1, 0, 4, 4)
        self.tips_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.tips_lab.setMaximumSize(QtCore.QSize(130, 15))
        self.tips_lab.setObjectName("tips_lab")
        self.gridLayout.addWidget(self.tips_lab, 0, 0, 1, 1)
        self.tabWidget.addTab(self.email_tab, "")
        self.time_tab = QtWidgets.QWidget()
        self.time_tab.setObjectName("time_tab")
        self.time_list = QtWidgets.QListWidget(self.time_tab)
        self.time_list.setGeometry(QtCore.QRect(10, 10, 231, 271))
        self.time_list.setObjectName("time_list")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.time_list.addItem(item)
        self.creater_reminder_btn = QtWidgets.QPushButton(self.time_tab)
        self.creater_reminder_btn.setGeometry(QtCore.QRect(250, 10, 75, 23))
        self.creater_reminder_btn.setObjectName("creater_reminder_btn")
        self.del_reminder_btn = QtWidgets.QPushButton(self.time_tab)
        self.del_reminder_btn.setGeometry(QtCore.QRect(250, 50, 75, 23))
        self.del_reminder_btn.setObjectName("del_reminder_btn")
        self.up_btn = QtWidgets.QPushButton(self.time_tab)
        self.up_btn.setGeometry(QtCore.QRect(250, 90, 75, 23))
        self.up_btn.setObjectName("up_btn")
        self.down_btn = QtWidgets.QPushButton(self.time_tab)
        self.down_btn.setGeometry(QtCore.QRect(250, 130, 71, 21))
        self.down_btn.setObjectName("down_btn")
        self.save_reminder_btn = QtWidgets.QPushButton(self.time_tab)
        self.save_reminder_btn.setGeometry(QtCore.QRect(250, 170, 75, 23))
        self.save_reminder_btn.setObjectName("save_reminder_btn")
        self.label = QtWidgets.QLabel(self.time_tab)
        self.label.setGeometry(QtCore.QRect(250, 210, 141, 31))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.time_tab, "")
        Settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.save_email_btn.setText(_translate("Settings", "保存"))
        self.del_email_btn.setText(_translate("Settings", "删除"))
        self.add_email_btn.setText(_translate("Settings", "添加"))
        self.sender_lab.setText(_translate("Settings", "发信名称"))
        self.password_lab.setText(_translate("Settings", "密码"))
        self.ssl_lab.setText(_translate("Settings", "ssl端口"))
        self.email_lab.setText(_translate("Settings", "Email地址"))
        self.default_email_btn.setText(_translate("Settings", "默认使用"))
        __sortingEnabled = self.email_list.isSortingEnabled()
        self.email_list.setSortingEnabled(False)
        item = self.email_list.item(0)
        item.setText(_translate("Settings", "furnace_0xg@163.com"))
        item = self.email_list.item(1)
        item.setText(_translate("Settings", "2057567309@qq,com"))
        self.email_list.setSortingEnabled(__sortingEnabled)
        self.tips_lab.setText(_translate("Settings", "暂仅支持stmp"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.email_tab), _translate("Settings", "邮箱设置"))
        __sortingEnabled = self.time_list.isSortingEnabled()
        self.time_list.setSortingEnabled(False)
        item = self.time_list.item(0)
        item.setText(_translate("Settings", "15分钟"))
        self.time_list.setSortingEnabled(__sortingEnabled)
        self.creater_reminder_btn.setText(_translate("Settings", "新建"))
        self.del_reminder_btn.setText(_translate("Settings", "删除"))
        self.up_btn.setText(_translate("Settings", "上移"))
        self.down_btn.setText(_translate("Settings", "下降"))
        self.save_reminder_btn.setText(_translate("Settings", "保存"))
        self.label.setText(_translate("Settings", "前三个时间会\n"
"在主窗口的右键菜单显示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.time_tab), _translate("Settings", "提醒时间"))

